export enum OperationType {
  DEFAULT = 'DEFAULT',
  BATCH_FILES = 'BATCH_FILES',
  REMOVE_FILE = 'REMOVE_FILE',
  REMOVE_FILE_LINE = 'REMOVE_FILE_LINE',
  MODIFY_JSON = 'MODIFY_JSON',
  REMOVE_DIRECTORY = 'REMOVE_DIRECTORY',
}
