export const OPERATION_TYPE = {
  DEFAULT: 'DEFAULT',
  REMOVE_FILE: 'REMOVE_FILE',
  REMOVE_FILE_LINE: 'REMOVE_FILE_LINE',
  BATCH_FILES: 'BATCH_FILES',
  MODIFY_JSON: 'MODIFY_JSON',
  REMOVE_DIRECTORY: 'REMOVE_DIRECTORY',
};
